require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'example' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'exampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  inhibit_all_warnings!

  pod 'LocoKit', :git => 'https://github.com/sobri909/LocoKit.git', :branch => 'master'
  pod 'LocoKit/Base', :git => 'https://github.com/sobri909/LocoKit.git', :branch => 'master'
  pod 'SwiftNotes'
  pod 'GRDB.swift', '~> 4.14.0'

  post_install do |installer|
    ##
    installer.pods_project.targets.each do |target|
      if ['Upsurge'].include? "#{target}"
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.0'
        end
      end
    end

    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
